#ifndef WL_H
#define WL_H

#include <stdbool.h>
#include <stdint.h>

#define VK_USE_PLATFORM_WAYLAND_KHR
#include <vulkan/vulkan.h>

#include <wayland-client.h>
#include "xdg-shell-client-protocol.h" // generated by wayland scanner

// Wl holds the needed wayland connections.
struct Wl {
    struct wl_display* display;
    struct wl_registry* registry;
    struct wl_compositor* compositor;
    struct xdg_wm_base* wm_base;

    // window
    struct wl_surface* surface;
    struct xdg_surface* xdg_surface;
    struct xdg_toplevel* xdg_toplevel;

    int32_t width;
    int32_t height;

    // state
    bool configured; // got first xdg_surface.configure
    bool should_close;
};

// wl_init connects, and binds the compositor,
// xdg wm base, and creates the surface.
// Returns true on success and false on failure.
bool wl_init(struct Wl* wl);

// wl_finish disconnects and destroys the surface.
void wl_finish(struct Wl* wl);

#endif
